"""add votes points attendance bookmarks categories

Revision ID: 9f2f55308ae8
Revises: c8399c9dc326
Create Date: 2026-05-27 15:13:21.458312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2f55308ae8'
down_revision: Union[str, None] = 'c8399c9dc326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.create_table('point_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('ATTENDANCE', 'POST_UPVOTE_RECEIVED', 'POST_DOWNVOTE_RECEIVED', 'COMMENT_UPVOTE_RECEIVED', 'COMMENT_DOWNVOTE_RECEIVED', 'POST_CREATED', 'COMMENT_CREATED', name='pointreason'), nullable=False),
    sa.Column('reference_vote_id', sa.UUID(), nullable=True),
    sa.Column('reference_post_id', sa.UUID(), nullable=True),
    sa.Column('reference_comment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_created_at'), 'point_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_transactions_reference_comment_id'), 'point_transactions', ['reference_comment_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_reference_post_id'), 'point_transactions', ['reference_post_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id')
    )
    op.create_index(op.f('ix_bookmarks_post_id'), 'bookmarks', ['post_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('post_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.Enum('UP', 'DOWN', name='votetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id')
    )
    op.create_index(op.f('ix_post_votes_post_id'), 'post_votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_votes_user_id'), 'post_votes', ['user_id'], unique=False)
    op.create_table('comment_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.Enum('UP', 'DOWN', name='votetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id')
    )
    op.create_index(op.f('ix_comment_votes_comment_id'), 'comment_votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_votes_user_id'), 'comment_votes', ['user_id'], unique=False)
    op.add_column('comments', sa.Column('up_votes', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('comments', sa.Column('down_votes', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('posts', sa.Column('up_votes', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('posts', sa.Column('down_votes', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.execute(sa.text("CREATE TYPE category AS ENUM ('DOMESTIC_SOCCER', 'INTL_SOCCER', 'DOMESTIC_BASEBALL', 'INTL_BASEBALL', 'DOMESTIC_STOCK', 'INTL_STOCK', 'CRYPTO')"))
    op.add_column('posts', sa.Column('category', sa.Enum('DOMESTIC_SOCCER', 'INTL_SOCCER', 'DOMESTIC_BASEBALL', 'INTL_BASEBALL', 'DOMESTIC_STOCK', 'INTL_STOCK', 'CRYPTO', name='category', create_type=False), nullable=True))
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_column('posts', 'category')
    op.execute(sa.text("DROP TYPE IF EXISTS category"))
    op.drop_column('posts', 'down_votes')
    op.drop_column('posts', 'up_votes')
    op.drop_column('comments', 'down_votes')
    op.drop_column('comments', 'up_votes')
    op.drop_index(op.f('ix_comment_votes_user_id'), table_name='comment_votes')
    op.drop_index(op.f('ix_comment_votes_comment_id'), table_name='comment_votes')
    op.drop_table('comment_votes')
    op.drop_index(op.f('ix_post_votes_user_id'), table_name='post_votes')
    op.drop_index(op.f('ix_post_votes_post_id'), table_name='post_votes')
    op.drop_table('post_votes')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_post_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_reference_post_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_reference_comment_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_created_at'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_attendances_user_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
